name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: sohini340
          ecr: false
          logout: true  # Ensure logout after job completion

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sohini340/llm-automation-agent:$(date +%s)
      - name: Push the docker image
        run: docker push the sohini340/llm-automation-agent
